server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-server
zuul:
  routes:
    prefix: /route #添加路由前缀
    api-a:
      path: /api-a/** #映射路径 访问路径规则
      serviceId: eureka-client #指定服务端的名称
      strip-prefix: true #代理前缀默认会从请求路径中移除，通过该设置关闭移除功能
      #url: http://127.0.0.1:8080 #映射路径对应的实际的url地址
    api-b:
      path: /api-b/**
      serviceId: feign-client
  ignored-services: user-service #想要禁用某一个路由规则
