version: '3'
services:
  eureka-server:
    image: eureka-server
    restart: always
    ports:
      - 8761:8761

  config-server:
    image: config-server
    restart: always
    ports:
      - 8888:8888
#  docker-compose -f docker-compose.yml up
#  docker-compose -f docker-compose.yml down