spring:
  application:
    name: springcloud-paymentservice
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.common.entity