server:
  port: 9527
eureka:
  instance:
    hostname: api-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path_route1 #路由id唯一
          uri: http://localhost:8001 #提供服务的目标服务地址
          predicates: #断言 路径相匹配的进行路由
            - Path=/pay/getPaymentById/** #路由规则   与或非 RoutePredicateFactory Before After Between Cookie Header Host Method
        - id: path_route2
          uri: http://localhost:8001
          predicates:
            - Path=/pay/getPayments/**
        - id: path_route3
          uri: lb://springcloud-paymentservice
          predicates:
            - Path=/pay/getServerPort/**
            - After=2021-08-04T14:46:44.367-08:00[Asia/Shanghai]
            - Before=2021-08-04T15:46:44.367-08:00[Asia/Shanghai]
            - Cookie=chocolate, red
            - Header=X-Request-Id, \d+
            - Host=**.somehost.org,**.anotherhost.org
            - Method=GET,POST
            - Query=green
            - RemoteAddr=192.168.1.1/24
            - Weight=group1, 2
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
  application:
    name: api-gateway
logging:
  level:
    org.springframework.cloud.gateway: debug