server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #配置文件所在目录，classpath（类路径）和（系统文件路径） file两种
          #search-locations: file:D:\config
          search-locations: classpath:/config
        #git:
          #uri: https://github.com/futureofpossible/repo.git #配置git仓库地址https://github.com/futureofpossible/repo.git
          #search-paths: /** #配置仓库路径
          #username: 342707539@qq.com #访问git仓库的用户名
          #password: bing520mei #访问git仓库的用户密码
          #skip-ssl-validation: true
          #default-label: main
      #label: main #配置仓库的分支 master
      #Cannot clone or checkout repository: https://github.com/futureofpossible http://localhost:8888/config-server/dev
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties