#单机模式
server:
  port: 8761
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false   #是否将自己注册到Eureka中
    fetch-registry: false         #是否从Eureka中获取信息 维护服务实例并不需要去检索服雾
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true #表示注册中心是否开启服务的自我保护能力。 自我保护机制
    renewal-percent-threshold: 0.85 #表示 Eureka Server 开启自我保护的系数，默认：0.85。
    eviction-interval-timer-in-ms: 60000 #表示 Eureka Server 清理无效节点的频率，默认 60000 毫秒（60 秒）。服务节点移除
spring:
  application:
    name: eureka-server #表示应用名称，在注册中心中显示的服务注册名称。